# Logistic Regression

## Import the libraries

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Spliting the datset into training set and test set

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

Feature scaling is must for the logistic regression

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Tranining the logistic Regression model on the training set

In [42]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting a new result

In [43]:
info = [[30, 40000]]
print(classifier.predict(sc.transform(info)))

[0]


## Predicting the probability

In [44]:
print(classifier.predict_proba(sc.transform(info)))

[[0.97276407 0.02723593]]


## Predicting the test set

In [45]:
y_pred = classifier.predict(X_test)

In [46]:
## concatinate to better visualization
y_pred = y_pred.reshape(len(y_pred), 1)
y_test = y_test.reshape(len(y_test), 1)
np.concatenate((y_pred, y_test), axis = 1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0,

## Making the confusion matrix and accuaracy score

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[65  3]
 [ 8 24]]


0.89

## Finding out the statistically significant predictor

In [48]:
import statsmodels.api as sm

In [53]:
ones = np.ones((300, 1)).astype(int)
new_X = np.append(arr = ones, values = X_train, axis = 1)

In [54]:
# Building the model
log_reg = sm.Logit(y_train, new_X).fit()

Optimization terminated successfully.
         Current function value: 0.371982
         Iterations 7


In [56]:
# Printing summary table
print(log_reg.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                  300
Model:                          Logit   Df Residuals:                      297
Method:                           MLE   Df Model:                            2
Date:                Thu, 12 Feb 2026   Pseudo R-squ.:                  0.4355
Time:                        19:48:41   Log-Likelihood:                -111.59
converged:                       True   LL-Null:                       -197.69
Covariance Type:            nonrobust   LLR p-value:                 4.080e-38
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.0034      0.183     -5.479      0.000      -1.362      -0.644
x1             2.2667      0.289      7.831      0.000       1.699       2.834
x2             1.2134      0.208      5.821      0.0